package media

import (
	"sort"
	"strings"
)

// emotionToPhysical maps abstract mood words (model-opaque) to visible body/face motion.
// Longer keys first — applied by rewriteEmotionToPhysical.
var emotionToPhysical = map[string]string{
	// Chinese multi-char first
	"悲愤欲绝": "双手握拳、牙关咬紧、肩膀起伏",
	"几近破碎": "身体下沉、膝盖发软、扶住旁边",
	"情绪崩溃": "肩膀剧烈耸动、双手捂脸、身体前倾",
	"滔天怒火": "握拳上提、脚步前冲、胸口猛起伏",
	"杀意沸腾": "身体前倾压低、目光盯死对方、嘴角下压",
	"心境崩塌": "低头、手指松开、身体后坐",
	"怒火中烧": "咬紧后牙、脖子青筋微紧、拳头收紧",
	"怒不可遏": "猛地起身、一脚迈前、手臂甩开",
	"气势逼人": "挺胸逼近半步、下巴抬高、直视对方",
	"杀气腾腾": "步伐沉重逼近、拳头紧握、视线锁定",
	"泪流满面": "眼眶蓄泪溢出、脸颊湿痕、低头",
	"热泪盈眶": "眨眼几次、眼角湿亮、下巴微颤",
	"泣不成声": "肩膀抖动、胸口起伏加快、用手背擦眼",
	"强忍着泪": "眨眼压制、下唇咬住、仰头吸气",
	"强装镇定": "双手垂放贴身、深呼吸一次、目光平视",
	"故作轻松": "嘴角上扬一瞬又落下、肩膀放松、手插进口袋",
	"冷笑一声": "唇角单边上提、鼻翼轻抽、目光斜视",
	"满脸错愕": "双眼睁大、眉心上提、身体后仰半寸",
	"震惊不已": "眼睛骤然睁大、身体僵住半秒、嘴微张",
	"惊恐万状": "后退一步、双手护在胸口前、呼吸急促",
	"难以置信": "连连摇头、后退半步、手指发抖",
	"沉痛万分": "低头、双手垂落、脚步放慢",
	"痛不欲生": "双膝跪地、双手撑地、头低到近地",
	"温柔体贴": "伸手轻触对方手臂、身体侧向靠近",
	"柔情似水": "目光跟随对方、身体微微前倾",
	"暧昧不清": "指尖轻碰对方手背、身体靠近半步",
	"激情澎湃": "手臂大幅度挥动、脚步加快、胸口起伏",
	"怒视前方": "双眼盯死前方、眉头压低、脖子微前倾",
	"怒视":     "双眼盯死、眉头压低、嘴角下沉",
	"凝视":     "双眼固定盯住、眨眼减少、头部微倾",
	"冷漠":     "表情不动、目光平直、身体距离拉开",
	"冷笑":     "唇角单边上提、眼睛眯起",
	"狞笑":     "嘴角大幅上扬、牙齿露出、眼睛眯窄",
	"微笑":     "嘴角两侧上提、眼睛微眯",
	"苦笑":     "嘴角勉强上提一下又落下、眉心微皱",
	"傻笑":     "嘴角拉开、眼睛弯起、晃一下头",
	"大笑":     "张嘴、肩膀抖动、头向后仰",
	"狂笑":     "张大嘴、身体前倾后仰、拳头拍自己腿",
	"惨笑":     "嘴角歪一下、眼睛半闭、头缓慢摇动",
	"嘲讽":     "单边嘴角上扬、下巴微抬、斜眼看人",
	"轻蔑":     "下巴抬起、鼻翼轻抽、视线从上扫过",
	"不屑":     "嘴角下撇、转开视线、肩膀一耸",
	"鄙夷":     "鼻子轻哼一下、头侧开、后退半步",
	"愤怒":     "眉头下压、拳头握紧、胸口起伏加快",
	"暴怒":     "猛然起立、手臂甩开、踩前一步",
	"震怒":     "一拳砸向桌面或空气、身体前倾",
	"恼怒":     "咬牙、手指敲桌或握拳、脚步踏重",
	"生气":     "眉心皱起、嘴抿紧、呼气加重",
	"恼火":     "手背拍一下大腿、头偏向一侧",
	"崩溃":     "双手抱头、身体蹲下、肩膀乱颤",
	"绝望":     "双手松开垂落、跪坐下、头缓慢低下",
	"悲伤":     "嘴角下垂、眼睑半合、肩膀内收",
	"悲痛":     "双手捂住胸口、身体前倾弯腰",
	"哀伤":     "缓慢低头、手背擦过眼角、脚步拖慢",
	"难过":     "目光下移、咬下唇、手指绞在一起",
	"委屈":     "咬住下唇、眼睛下垂、肩膀往内缩",
	"恐惧":     "后退、双手护胸、瞳孔睁大",
	"害怕":     "身体后缩、膝盖发软、抓住旁边物体",
	"惊恐":     "猛退一步、双手抬到胸前、呼吸急促",
	"慌乱":     "左右张望、手脚无措摆动、脚步碎乱",
	"紧张":     "手指搓动、吞咽一下、肩膀抬高",
	"焦虑":     "来回踱步、手指敲击、频繁眨眼",
	"尴尬":     "摸后脑勺、目光躲开、干笑一下",
	"羞涩":     "低头、耳尖红、手指绞衣角",
	"羞愤":     "脸侧转开、拳头握紧、脚步后撤",
	"惊喜":     "双眼睁大、双手上抬、身体向前一小步",
	"激动":     "双手挥动、脚步加快、胸口起伏明显",
	"兴奋":     "拍手或握拳上提、脚跟轻跳一下",
	"喜悦":     "嘴角上扬、眼睛弯起、身体轻晃",
	"开心":     "嘴角上扬、肩膀放松、步伐变轻",
	"开心起来":   "嘴角上扬、点头、手轻拍大腿",
	"安心":     "肩膀放下、呼出一口气、闭上眼再睁开",
	"释然":     "肩膀放松下沉、嘴角微松、点一下头",
	"坚定":     "下巴抬起、脚步站稳、目光直视",
	"决绝":     "猛地转身、手臂甩开、大步离开",
	"犹豫":     "脚步停住又起步、手伸出去又收回",
	"犹豫不决":   "原地踏步两下、手抬起又放下",
	"震惊":     "眼睛睁圆、身体僵住、手停在半空",
	"吃惊":     "身体后仰、嘴微张、眉毛上挑",
	"惊讶":     "眉毛上挑、眼睛睁大、头微后仰",
	"疑惑":     "眉心微皱、头侧歪、视线左右扫",
	"困惑":     "眉头拧起、手放在下巴、轻微摇头",
	"愧疚":     "目光下移、避开对方眼睛、手指抠衣边",
	"懊悔":     "用手捂额头、摇头、身体前倾",
	"嫉妒":     "牙关轻咬、目光斜刺、拳头在身侧握紧",
	"恨意":     "手指抠进掌心、目光死盯、下颌绷紧",
	"怨恨":     "嘴角下压、眼神盯人不动、肩膀绷紧",
	"怨气":     "猛地呼气、头甩向一侧、手甩开",
	"威压":     "身体向前压迫、影子压住对方、目光不移开",
	"压迫感":    "镜头推近胸口与脸、人物身体前倾",
	"气场":     "站直、下巴抬、脚步停稳",
	"杀气":     "目光锁定、脚步下沉逼近、拳头紧握",
	"杀意":     "身体前倾、目光盯死、下颌绷紧",
	"心碎":     "双手按胸口、身体弯下、膝盖微曲",
	"心疼":     "伸手想触碰对方肩膀、眉心皱起、身体前倾",
	"心酸":     "鼻子轻抽、眨眼、嘴角向下抿",
	"心沉":     "胸口起伏变慢、目光失焦、肩膀下垂",
	"心动":     "眼睛跟着对方移动、身体不自觉前倾",
	"愣住":     "动作骤停、眼睛瞪住、手脚停在原地",
	"发愣":     "目光发直、眨眼变少、手垂着不动",
	"发呆":     "目光固定一点、嘴微张、身体静止",
	"沉默":     "嘴巴紧闭、不做口型、只做点头或摇头",
	"无言":     "嘴唇抿住、转开脸、深呼吸一次",
	"平静":     "呼吸匀速、肩膀放松、目光平稳",
	"平静下来":   "肩膀下沉、呼气放慢、双手放下",
	"温柔":     "手指动作放慢、身体靠近、触碰轻",
	"狠厉":     "手腕快速甩动、脚步踩实、眼神盯死",
	"狠毒":     "嘴角勾起、手指指向对方、步伐逼近",
	"阴狠":     "眼睛眯起、头微低、从下往上看人",
	"阴沉":     "眉头压低、灯光侧打脸、走动放慢",
	"阴冷":     "身体离开、目光斜扫、嘴角不动",
	"凌厉":     "眼神直盯、转身干净利落、手臂快切动作",
	"犀利":     "目光对焦点、手指指向痛处、说话时下巴前送",
	"犀利目光":   "眼睛盯住对方眼睛、眨眼少、头不动",
	"深情":     "眼睛不离开对方脸、身体缓缓靠近",
	"深沉":     "低头思考片刻、手指搭在桌面、呼吸放缓",
	"沉重":     "脚步放慢加重、肩膀下沉、头略低",
	"压抑":     "胸口起伏变浅、肩膀内扣、呼吸变短",
	"氛围压抑":   "光线变暗、人物距离拉开、动作放慢",
	"气氛凝重":   "人物静止更多、走动放慢、对视停顿",
	"沉重气氛":   "脚步放慢、对话停顿、灯光变冷",
	"无风起浪":   "灰尘微动、布帘轻晃、人物停住",
	"神念":     "手指轻点虚空、目光聚焦远处一点",
	"情绪":     "面部肌肉位移、肩膀随呼吸起伏",
	"情感":     "眉眼口型变化、双手有明确位移",
	"感情":     "身体朝向对方、触碰或拉开距离",
	"感动":     "眼眶湿、喉咙吞咽、双手交握",
	"感慨":     "抬头望远处、呼气、轻轻摇头",
	"感伤":     "低头、手指抚过旧物、脚步放慢",
	"情不自禁":   "身体猛然靠近、手伸出去抓住对方",
	"情难自禁":   "身体前倾拉近、手指颤抖触碰",
	"冲动":     "猛然起身冲前、手臂伸出推或抓",
	"冷静":     "动作变慢、呼吸放稳、视线移开再回来",
	"淡定":     "慢慢坐下或站稳、双手交叉、目视前方",
	"轻松":     "肩膀放松、手脚自然摆动、步子变轻",
	"痛苦":     "眉头紧皱、嘴角扯开、身体蜷缩",
	"难受":     "用手压住胸口或腹部、弯腰、呼吸不稳",
	"慌张":     "脚步乱、手乱抓物品、头左右转",
	"怔忪":     "目光发直、嘴微张、手停在半空",
	"怔住":     "整个人定住、眼睛圆睁、不眨眼",
	"愕然":     "头后仰、眼睛睁大、退半步",
	"尴尬笑":    "嘴角扯一下、别开脸、手摸鼻子",
	"强颜欢笑":   "嘴角硬抬、眼睛没弯、点头过快",
	"若有所思":   "手指点下巴、目光移开、轻微点头",
	"意味深长":   "缓慢点头、停顿后看对方、嘴角微动",
	"深吸一口气":  "胸口明显鼓起再落下、肩膀随之起伏",
	"松了口气":   "肩膀下沉、嘴张开呼气、眼睛半闭一下",

	// English abstract → physical
	"emotional close-up":       "tight face fill frame, brows lids lips move",
	"peak emotion":             "brows press down, lids tighten, jaw clench",
	"rising emotion":           "chest rises faster, shoulders lift, chin pushes forward",
	"emotional beats":          "clear face muscle changes and hand moves on beats",
	"emotion":                  "brows lids lips and shoulders move",
	"emotional":                "brows lids lips shift",
	"tense atmosphere":         "subjects freeze then micro-shift weight",
	"tension":                  "shoulders rise, fists tighten, stance narrows",
	"intensity":                "faster breathing motion, firmer jaw, tighter fists",
	"intense":                  "jaw set, gaze locked, stance planted",
	"dramatic":                 "one decisive body move then hold",
	"melancholy":               "head lowers, shoulders roll inward, slow blink",
	"sorrow":                   "corners of mouth drop, eyes lower, slow exhale",
	"grief":                    "knees soften, hands cover face, body folds forward",
	"rage":                     "fists clench, step forward, chest heaves",
	"fury":                     "arm swings hard, foot stomps, jaw thrusts",
	"anger":                    "brows knit, teeth press, fist closes",
	"fear":                     "steps back, hands guard chest, eyes widen",
	"terror":                   "scrambles back, hands up, knees buckle",
	"joy":                      "mouth corners lift, eyes squint, light bounce in step",
	"happiness":                "smile forms, shoulders drop, steps lighten",
	"love":                     "leans in, soft hand reach, eyes stay on face",
	"romantic":                 "bodies close distance half a step, hands nearly touch",
	"sad":                      "mouth droops, gaze drops, shoulders cave",
	"lonely":                   "stands apart, arms hang, looks to empty side",
	"nervous":                  "fingers fidget, swallows, weight shifts foot to foot",
	"anxious":                  "paces short path, taps fingers, blinks fast",
	"shocked":                  "eyes snap wide, body freezes, hands mid-air",
	"surprised":                "brows up, lips part, torso leans back",
	"confused":                 "head tilts, brows pinch, eyes scan left right",
	"determined":               "chin up, feet plant, eyes push forward",
	"heartbroken":              "hand presses chest, body folds, breath hitch",
	"vulnerable":               "shoulders exposed forward, arms loose, chin tucked",
	"powerful":                 "chest open, stride heavy, camera below chin",
	"menacing":                 "advances slowly, head low, eyes stay locked",
	"sinister":                 "half-smile, head tilts down, eyes from under brow",
	"atmosphere":               "dust or light drifts while bodies hold pose",
	"mood":                     "pose and eye direction stay readable",
	"feeling":                  "visible limb and face muscle change only",
	"feelings":                 "visible limb and face muscle change only",
}

var emotionKeysLongestFirst []string

func init() {
	emotionKeysLongestFirst = make([]string, 0, len(emotionToPhysical))
	for k := range emotionToPhysical {
		emotionKeysLongestFirst = append(emotionKeysLongestFirst, k)
	}
	sort.Slice(emotionKeysLongestFirst, func(i, j int) bool {
		return len([]rune(emotionKeysLongestFirst[i])) > len([]rune(emotionKeysLongestFirst[j]))
	})
}

// rewriteEmotionToPhysical replaces opaque emotion words with concrete physical motion.
func rewriteEmotionToPhysical(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	for _, k := range emotionKeysLongestFirst {
		if strings.Contains(s, k) {
			s = strings.ReplaceAll(s, k, emotionToPhysical[k])
		}
	}
	// Collapse leftover double punctuation / spaces from replacements.
	s = strings.ReplaceAll(s, "  ", " ")
	s = strings.ReplaceAll(s, "，，", "，")
	s = strings.ReplaceAll(s, ",,", ",")
	return strings.TrimSpace(s)
}
